### PR TITLE
UYse updated eyes-images version + bump major

### PR DESCRIPTION
**Pull request by jonathanadler**
Required according to Applitools:

https://help.applitools.com/hc/en-us/articles/360038739612?mkt_tok=eyJpIjoiTm1FNFpqZzBNamhsT1RBMyIsInQiOiJkWUtneVFRNkV5RTB4NHI2VmxhYUZacWtjNTdWc0hhbDg2SDNYOFgrTjJyek1VTDB5VFhZMGNRXC91VDBZblpcL2RTbGpuNk04cFFhY05VYzQzMnBlXC9Nc2cxV1pPTytJMkFTS1M1QUpOTUk3a0xWWEVubGJPcnV1ODBvZWQwUGs1OSJ9

### CODE REVIEW

**Review by yanivefraim — CHANGES_REQUESTED** [review]
This one might be a breaking change (a major eyes version).

I guess that we should bump major as well?

* also, please see the error here: 
https://travis-ci.org/wix-incubator/match-screenshot/builds/653083879?utm_source=github_status&utm_medium=notification

**Comment by jonathanadler** [comment]
> This one might be a breaking change (a major eyes version).
> 
> I guess that we should bump major as well?
> 
> * also, please see the error here:
>   https://travis-ci.org/wix-incubator/match-screenshot/builds/653083879?utm_source=github_status&utm_medium=notification

I thought about this, but aren't the tests enough?
I'm just worried it will take a long time for developers to update.

**Comment by jonathanadler** [comment]
@yanivefraim 
ok I fixed the test + bumped the version

**Review by yanivefraim — APPROVED** [review]
Awesome, thanks for the PR! 👑

**Pull request merged**
